# -*- coding: utf-8 -*-
"""VendingMachine.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i4G4-rxnDs45VB8qEYG4m1VBnE-0t6uJ
"""

# Program VendingMachine
# Spesifikasi: Program yang dapat mengeluarkan makanan/minuman berdasarkan 
# pilihan pelanggan dan uang yang masuk dalam mesin

# KAMUS 
# uang100k : integer {variabel untuk input jumlah uang pecahan 100.000}
# uang50k : integer {variabel untuk input jumlah uang pecahan 50.000}
# uang20k : integer {variabel untuk input jumlah uang pecahan 20.000}
# uang10k : integer {variabel untuk input jumlah uang pecahan 10.000}
# uang5k : integer {variabel untuk input jumlah uang pecahan 5.000}
# totalUang : integer {variabel untuk total uang yang dimasukkan}
# dataVM : matrix of str and int {variabel untuk data barang yang ada di Vending Machine}
# listPesanan : array [0..19] of integer {array yang mendefinisikan list makanan dan minuman}
# sisaUang : integer {variabel untuk menentukan sisa uang yang keluar dari Vending Machine}
# loopBeliBarang : boolean {variabel untuk perulangan beli barang atau tidak}
# adaPesanan : boolean {variabel untuk penanda ada atau tidaknya pesanan}
# no : integer {variabel untuk penomoran barang}
# item : array [0..2] of string and integer {array yang mendefinisikan data masing-masing barang}
# nomorBarang : integer {variabel untuk menyimpan nomor barang yang dipilih}
# jumlahBarang : integer {variabel untuk menyimpan jumlah barang yang dipilih}
# adaStok : boolean {variabel untuk menyimpan hasil fungsi CekStok}
# adaUang : boolean {variabel untuk menyimpan hasil fungsi CekUang}
# masihBeli : integer {variabel untuk menyimpan pilihan masih membeli barang atau tidak}
# cetakStruk : integer {variabel untuk menyimpan pilihan ingin cetak struk atau tidak}
# hargaTotal : integer {variabel untuk menyimpan harga total semua barang yang dibeli}
# hargaTotalItem : integer {variabel untuk menyimpan harga total satu item}

# Fungsi CekStok
def CekStok(data, nomor, jumlahPesanan):
    # Fungsi untuk mengecek stok yang tersedia

    # ALGORITMA
    return jumlahPesanan <= data[nomor - 1][2]

# Fungsi CekUang
def CekUang(data, nomor, jumlahPesanan, uang):
    # Fungsi untuk mengecek uang yang dimiliki pembeli

    # ALGORITMA
    return (data[nomor - 1][1] * jumlahPesanan) <= uang

# ALGORITMA
# 1. Uang masuk
# Memasukkan berbagai kemungkinan pecahan uang
print("\nMasukkan Jumlah Pecahan Uang")
uang100k = int(input("100.000\t: "))
uang50k = int(input("50.000\t: "))
uang20k = int(input("20.000\t: "))
uang10k = int(input("10.000\t: "))
uang5k = int(input("5.000\t: "))

# Menghitung total uang yang dimasukkan
totalUang = ((uang100k * 100000)
             + (uang50k * 50000)
             + (uang20k * 20000)
             + (uang10k * 10000)
             + (uang5k * 5000))
print(f"\nJumlah Uang Anda: {totalUang}")


# Data barang yang ada di Vending Machine
# Indeks ke-0: Nama Makanan/Minuman
# Indeks ke-1: Harga
# Indeks ke-2: Stok
dataVM = [
    ["Makanan 1", 5000, 10],
    ["Makanan 2", 5000, 7],
    ["Makanan 3", 5000, 9],
    ["Makanan 4", 5000, 8],
    ["Makanan 5", 5000, 5],
    ["Makanan 6", 10000, 10],
    ["Makanan 7", 10000, 10],
    ["Makanan 8", 10000, 1],
    ["Makanan 9", 10000, 3],
    ["Makanan 10", 10000, 5],
    ["Minuman 1", 5000, 2],
    ["Minuman 2", 5000, 3],
    ["Minuman 3", 5000, 5],
    ["Minuman 4", 5000, 5],
    ["Minuman 5", 5000, 10],
    ["Minuman 6", 10000, 9],
    ["Minuman 7", 10000, 10],
    ["Minuman 8", 10000, 8],
    ["Minuman 9", 10000, 10],
    ["Minuman 10", 10000, 1]
]


# List untuk menyimpan jumlah pesanan dari tiap-tiap barang
# Indeks ke-n adalah jumlah pesanan barang bernomor n + 1
listPesanan = [0 for i in range(len(dataVM))]


# 2. Loop pembelian barang
# Pembeli akan memasukkan nomor barang dan jumlah barang yang ingin dibeli
sisaUang = totalUang 
loopBeliBarang = True
adaPesanan = False
while loopBeliBarang:

    # 1. Menampilkan data barang
    print("\n" + "-" * 40)
    print(f"| NO. | {'NAMA BARANG':^15} | HARGA | STOK |")
    print("-" * 40)
    no = 1
    for item in dataVM:
        print(f"| {no:>3} | {item[0]:<15} | {item[1]:<5} | {item[2]:<4} |")
        no += 1
    print("-" * 40)

    # 2. Memasukkan nomor barang yang ingin dibeli
    nomorBarang = -1
    while (nomorBarang < 1) or (nomorBarang > len(dataVM)):
        nomorBarang = int(input("\nMasukkan Nomor Barang: "))
        if (nomorBarang < 1) or (nomorBarang > len(dataVM)):
            print("Nomor Barang Tidak Ditemukan")

    # 3. Memasukkan jumlah barang yang ingin dibeli
    jumlahBarang = -1
    while jumlahBarang < 1:
        jumlahBarang = int(input("\nMasukkan Jumlah Barang: "))
        if jumlahBarang < 1:
            print("Jumlah Barang Tidak Boleh Kurang Dari 1")

    # 4. Cek stok barang dan uang pembeli
    # Cek stok barang
    adaStok = CekStok(dataVM, nomorBarang, jumlahBarang)
    if adaStok:
        # Jika ada stok, cek uang pembeli
        adaUang = CekUang(dataVM, nomorBarang, jumlahBarang, sisaUang)
        if adaUang:
            # Jika ada stok dan uang pembeli cukup
            # 1. Mengurangi jumlah uang pembeli
            sisaUang -= (dataVM[nomorBarang - 1][1] * jumlahBarang)
            # 2. Mengurangi stok barang yang dipilih
            dataVM[nomorBarang - 1][2] -= jumlahBarang
            # 3. Menambahkan jumlah barang yang dipilih ke list pesanan barang
            listPesanan[nomorBarang - 1] += jumlahBarang
            # 4. Tandai sudah ada pesanan jika sebelumnya tidak ada pesanan
            if not adaPesanan:
                adaPesanan = True
            print("\n" + ("=" * 50))
            print(f"{'Pesanan Berhasil Diproses':^50}")
            print("=" * 50)
        else:
            # Jika uang pembeli tidak cukup
            print("\nMaaf, Uang Anda Tidak Cukup")
    else:
        # Jika tidak ada stok
        print("\nMaaf, Barang Tidak Tersedia")

    # 5. Menampilkan sisa uang pembeli
    print(f"\nSisa Uang Anda: {sisaUang}")

    # 6. Tanya apakah pembeli masih ingin membeli barang
    if sisaUang > 0:
        # Jika ada sisa uang, tanyakan
        masihBeli = -1
        while (masihBeli != 1) and (masihBeli != 0):
            print("\nApakah Masih Ingin Membeli Barang?")
            masihBeli = int(input("Ya (Tekan Angka 1)/Tidak (Tekan Angka 0): "))
            if (masihBeli != 1) and (masihBeli != 0):
                print("Angka yang Dimasukkan Salah")

        if masihBeli == 0:
            # Jika pembeli tidak ingin lagi membeli barang,
            # keluar dari loop pembelian barang
            loopBeliBarang = False
    else:
        # Jika tidak ada sisa uang, tidak perlu tanya dan
        # langsung keluar dari loop pembelian barang
        loopBeliBarang = False


# 3. Ambil pesanan
# Jika tidak ada pesanan, bagian ini dilewat
if adaPesanan:
    # Jika ada pesanan,
    # vending machine mengeluarkan barang pesanan
    print("\n" + ("=" * 50))
    print(f"{'Silakan Ambil Pesanan Anda':^50}")
    print("=" * 50)


# 4. Ambil sisa uang
# Jika tidak ada sisa uang, bagian ini dilewat
if sisaUang > 0:
    # Jika masih ada sisa uang,
    if adaPesanan:
        # Jika ada pesanan,
        # vending machine mengeluarkan uang kembalian
        print("\n" + ("=" * 50))
        print(f"{'Silakan Ambil Uang Kembalian Anda Sebesar '+ str(sisaUang):^50}")
        print("=" * 50)
    else:
        # jika tidak ada pesanan,
        # vending machine mengeluarkan kembali uang yang dimasukkan
        print("\n" + ("=" * 50))
        print(f"{'Silakan Ambil Kembali Uang Anda Sebesar '+ str(sisaUang):^50}")
        print("=" * 50)


# 5. Cetak struk
# Jika tidak ada pesanan, bagian ini dilewat
cetakStruk = -1
while adaPesanan and (cetakStruk != 1) and (cetakStruk != 0):
    # Jika ada pesanan,
    # tanya apakah pembeli ingin mencetak struk
    print("\nApakah Anda Ingin Mencetak Struk?")
    cetakStruk = int(input("Ya (Tekan Angka 1)/Tidak (Tekan Angka 0): "))
    if (cetakStruk != 1) and (cetakStruk != 0):
        print("Angka Yang Dimasukkan Salah")

# Jika pembeli menjawab ya, struk akan dicetak
if cetakStruk == 1:
    # Judul struk
    print("\n" + ("-" * 40))
    print(f"{'VENDING MACHINE STEI':^40}")
    print("-" * 40)
    # Daftar pembelian
    hargaTotal = 0
    for i in range(len(listPesanan)):
        if listPesanan[i] > 0:
            # Menghitung: harga total item = harga item x jumlah item yang dibeli
            hargaTotalItem = dataVM[i][1] * listPesanan[i]
            # Nama barang
            print(f"{dataVM[i][0]:<15}", end=" ")
            # Harga barang
            print(f"{dataVM[i][1]:<7}", end=" ")
            # Jumlah pembelian
            print(f"{listPesanan[i]:<3}", end=" ")
            # Harga total item
            print(f"{hargaTotalItem:>12}")
            # Menjumlahkan harga total dari semua item
            hargaTotal += hargaTotalItem
    # Total, tunai, dan kembali
    print(f"{('-' * 25):>40}")
    print(f"{'Total : ':>28}" + f"{hargaTotal:>12}")
    print(f"{'Tunai : ':>28}" + f"{totalUang:>12}")
    print(f"{'Kembali : ':>28}" + f"{sisaUang:>12}")
    print("-" * 40)


# 6. Ucapan terima kasih
print("\n" + ("=" * 50))
print(f"{'Terima Kasih':^50}")
print("=" * 50)

